---
title: "bigram analysis"
output: html_document
date: "2024-03-15"
---

We want to see how much of the results on the passivization dataset can be accounted for using just a bigram model.

```{r}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("analysis/bigram.Rmd")
library(here)
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(tidyr)
library(ggrepel)
library(gghalves)
library(colorBlindness)
library(showtext)
font_add("fira", "FiraSans-Regular.ttf")
font_add("firal", "FiraSans-Light.ttf")

theme_set(theme_light() + theme(text=element_text(size=14,  family="fira")))

```

```{r}
bigram <- read_csv(here("scores", "trigram.csv"))
mean_bigram <- bigram %>%
    group_by(verb, verb_class) %>%
    summarize(
        result = Hmisc::smean.cl.boot(pass_drop) %>% t() %>% as.data.frame()
    ) %>%
    unnest(result)

human_bigram_comparison <- mean_human_by_verb %>%
    left_join(mean_bigram, by = c("verb")) %>%
    mutate(verb_class = ifelse(verb_class == "Agent-patient", "Agent-Patient", verb_class)) %>%
    mutate(verb_class = ifelse(verb_class == "Experiencer-theme", "Experiencer-Theme", verb_class))
    
human_bigram_comparison %>%
    ggplot(aes(x = human_mean, y = Mean, xmin = human_error_1, xmax = human_error_2, ymin = Lower, ymax = Upper)) +
    geom_point(aes(color = verb_class)) +
    geom_smooth(aes(alpha=0.8), method="lm") +
    geom_errorbar(aes(color=verb_class, alpha=0.8)) +
    geom_errorbarh(aes(color=verb_class, alpha=0.8)) +
  xlab("Mean human passive drop") +
  ylab("Mean trigram model passive drop") +
  geom_text_repel(aes(label=verb), min.segment.length = 0, size=3.5, max.overlaps= Inf, segment.linetype = 2, family='firal', nudge_x = 1, nudge_y = 0.4) +
  theme(legend.position="bottom", legend.title = element_blank()) +
  scale_color_manual(values=verb_class_colours) +
#   scale_x_continuous(limits = c(-12, 100), breaks=seq(0, 80, by = 20)) +
#   scale_y_continuous(limits=c(-3,9), breaks=seq(0,8, by=2)) +
  guides(alpha="none", colour = guide_legend(nrow = 1))

ggsave(here("analysis", "trigram_correlation.pdf"), device="pdf", width=9, height=6, units = "in")

```

```{r}
human_bigram_comparison %>%
    select(human_mean, Mean) %>% cor()
```

```{r}

bigram %>%
    mutate(acc = pass_drop > 0) %>%
    group_by(verb, verb_class) %>%
    summarise(acc = sum(acc) / 5) %>%
    ggplot(aes(x = verb, y = acc)) +
    geom_bar(stat = "identity") +
    facet_wrap(vars(verb_class), scales="free_x")

bigram %>%
    mutate(acc = pass_drop > 0) %>%
    summarise(sum(acc)/n())

```