---
title: "human analysis"
output: html_document
date: "2024-03-15"
---

Human results

```{r}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("analysis/human_analysis.Rmd")
library(here)
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(tidyr)
library(ggrepel)
library(gghalves)
library(colorBlindness)
library(showtext)
library(patchwork)
source(here("analysis", "utils.R"))

font_add("fira", "FiraSans-Regular.ttf")
font_add("firal", "FiraSans-Light.ttf")

theme_set(theme_light() + theme(text=element_text(size=14,  family="fira")))

```

```{r}
human <- read_csv(here("scores", "human_results.csv"),
                  comment = "#",
                  col_names = c("reception_time", "md5_hash", "controller", "order_no", "", "trial_type", "",
                                "element_type", "element_name", "", "score", "", "", "group", "list", "frame_no", "verb",
                                "sentence_type", "sentence", "presentation_order", "is_passivizable", "id", "",""))

scores_human <- human %>% filter(element_type == "Scale", trial_type == "experimental-trial") %>%
  mutate(score = as.numeric(score),
         frame = as.numeric(frame_no),
         verb = factor(verb))


removed_participants <-  human  %>% 
  filter(element_type == "Scale") %>%
  filter((sentence_type == "check_accept" & score < 50) | 
           (sentence_type == "check_unaccept" & score > 50)) %>%
   count(id) %>% 
   filter(n>=15) %>% 
   select(id)

removed_participants %>% count(id)

scores_human <- scores_human %>% 
  filter(!id %in% removed_participants$id) %>%
  mutate(verb_class = get_verb_class(verb))

fillers_human <- human %>% 
  filter(element_type == "Scale", trial_type == "attention-check") %>%
  filter(!id %in% removed_participants$id) %>%
  mutate(score = as.numeric(score),
         verb = factor(verb),
         frame = order_no)

test_human <- scores_human %>%
    filter(element_type == "Scale", trial_type == "experimental-trial") %>%
    mutate(
        score = as.numeric(score),
        frame = as.numeric(frame_no),
        verb = factor(verb),
        verb_class = get_verb_class(verb)
    )

fillers_human %>%
    group_by(id) %>%
    summarise(n =n()) %>%
    filter(n != 70)

fillers_human %>%
    group_by(id, score) %>%
    summarise(n()) %>%
    ggplot(aes(x = score)) +
    geom_histogram() +
    facet_wrap(vars(id))
```

```{r}
fillers_human %>% ggplot(aes(x = score, fill=sentence_type)) +
    geom_histogram() +
    facet_wrap(vars(sentence))
```

```{r}

filler_variance <- fillers_human %>%
    group_by(sentence) %>%
    summarise(variance = sd(score)) %>%
    mutate(sentence_type = "filler")

variance_histogram <- test_human %>%
    group_by(verb, frame, sentence_type) %>%
    summarise(variance = sd(score)) %>%
    bind_rows(filler_variance) %>%
    mutate(sentence_type = factor(sentence_type, levels = c("active", "passive", "filler"))) %>%
    ggplot(aes(x = variance, fill = sentence_type)) +
    geom_histogram() +
    facet_wrap(vars(sentence_type)) +
    xlab("Inter-rater standard deviation") +
    ylab("Frequency") +
    scale_fill_manual(values = sent_type_colours) +
    theme(legend.position="none")

variance_histogram
```

```{r}
test_human %>%
    filter(sentence_type == "passive") %>%
    ggplot(aes(x = score, fill = frame)) +
    geom_histogram() +
    facet_wrap(vars(sentence))
```

```{r}
score_histogram <- test_human %>%
    filter(frame == 24) %>%
    ggplot(aes(x = score, fill = sentence_type)) +
    geom_histogram() +
    facet_grid(rows = vars(sentence_type), cols = vars(verb)) +
    xlab("Score") +
    ylab("Frequency") +
    scale_fill_manual(values = sent_type_colours, name=element_blank()) +
    theme(legend.position="none")
```

```{r}
variance_histogram + score_histogram
```

