---
title: "trigram analysis"
output: html_document
date: "2024-03-15"
---

## Section 4.6.2
We want to see how much of the results on the passivization dataset can be accounted for using just a trigram model.

```{r}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("analysis/exp1b_trigram.Rmd")
library(here)
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(tidyr)
library(ggrepel)
library(gghalves)
library(colorBlindness)
library(showtext)
font_add("fira", "FiraSans-Regular.ttf")
font_add("firal", "FiraSans-Light.ttf")

theme_set(theme_light() + theme(text=element_text(size=14,  family="fira")))

```

```{r}
trigram <- read_csv(here("scores", "exp1b_baselines", "trigram.csv"))
mean_trigram <- trigram %>%
    group_by(verb, verb_class) %>%
    summarize(
        result = Hmisc::smean.cl.boot(pass_drop) %>% t() %>% as.data.frame()
    ) %>%
    unnest(result)

human_trigram_comparison <- mean_pass_drop_human %>%
    left_join(mean_trigram, by = c("verb"), suffix = c("_human", "_trigram"))

human_trigram_comparison %>%
    ggplot(aes(x = Mean_human, xmin = Lower_human, xmax = Upper_human, 
               y = Mean_trigram, ymin = Lower_trigram, ymax = Upper_trigram)) +
    geom_point(aes(color = verb_class_human)) +
    geom_smooth(aes(alpha=0.8), method="lm") +
    geom_errorbar(aes(color=verb_class_human, alpha=0.8)) +
    geom_errorbarh(aes(color=verb_class_human, alpha=0.8)) +
  xlab("Mean human passive drop") +
  ylab("Mean trigram model passive drop") +
  geom_text_repel(aes(label=verb), min.segment.length = 0, size=3.5, max.overlaps= Inf, segment.linetype = 2, family='firal', nudge_x = 1, nudge_y = 0.4) +
  theme(legend.position="bottom", legend.title = element_blank()) +
  scale_color_manual(values=verb_class_colours) +
#   scale_x_continuous(limits = c(-12, 100), breaks=seq(0, 80, by = 20)) +
#   scale_y_continuous(limits=c(-3,9), breaks=seq(0,8, by=2)) +
  guides(alpha="none", colour = guide_legend(nrow = 1))

ggsave(here("analysis", "trigram_correlation.pdf"), device="pdf", width=9, height=6, units = "in")

```

### Correlation between human and trigram model

```{r}
human_trigram_comparison %>%
    ungroup() %>%
    select(Mean_human, Mean_trigram) %>%
  cor()
```

```{r}

trigram %>%
    mutate(acc = pass_drop > 0) %>%
    group_by(verb, verb_class) %>%
    summarise(acc = sum(acc) / 5) %>%
    ggplot(aes(x = verb, y = acc)) +
    geom_bar(stat = "identity") +
    facet_wrap(vars(verb_class), scales="free_x")

trigram %>%
    mutate(acc = pass_drop > 0) %>%
    summarise(sum(acc)/n())

```

## Add "really" before test verb to ensure that passive "WAS V-en" is not used.

```{r}
model_results <- 
  list.files(path = here("scores", "exp1b_baselines"), pattern = "*.csv", full.names = TRUE) %>%
  append(list.files(path=here("scores", "exp1b"), pattern="*.csv", full.names = TRUE))  %>%
  read_csv(id = "file_name") %>%
  mutate(file_name = (basename(file_name))) %>%
  mutate(really = ifelse(str_detect(file_name, "really"), "really", "original"))

model_results %>% select(file_name) %>% distinct()

# Select all ngram scores
ngram <- c("bigram.csv", "trigram.csv", "really_bigram.csv", "really_trigram.csv")
ngram_scores <- model_results %>% filter(file_name %in% ngram)

mean_ngram_scores <- ngram_scores %>%
  group_by(file_name, verb, verb_class) %>%
  summarise(
    result = Hmisc::smean.cl.boot(pass_drop) %>% t() %>% as.data.frame()
  ) %>%
  unnest(result) %>% 
  pivot_wider(id_cols = c(verb, verb_class), names_from = file_name, values_from = c(Mean, Lower, Upper))
  
mean_ngram_scores %>%
    ggplot(aes(x = Mean_bigram.csv, y = Mean_really_bigram.csv, color = verb_class)) +
    geom_point() +
    geom_errorbar(aes(ymin = Lower_really_bigram.csv, ymax = Upper_really_bigram.csv), width = 0, alpha = 0.3) +
    geom_errorbarh(aes(xmin = Lower_bigram.csv, xmax = Upper_bigram.csv), height = 0, alpha = 0.3) +
    geom_smooth(method = "lm", color = "black") +
    geom_text_repel(aes(label = verb), family="fira", color="black")
```

```{r}
non_ngram <- model_results %>% filter(!file_name %in% ngram)

mean_non_ngram_scores <- non_ngram %>%
  group_by(really, verb, verb_class) %>%
  summarise(
    result = Hmisc::smean.cl.boot(pass_drop) %>% t() %>% as.data.frame()
  ) %>%
  unnest(result) %>%
  pivot_wider(id_cols = c(verb, verb_class), names_from = really, values_from = c(Mean, Lower, Upper)) 

mean_non_ngram_scores %>%
  ggplot(aes(x = Mean_original, y = Mean_really, color = verb_class)) +
    geom_point() +
    geom_errorbar(aes(ymin = Lower_really, ymax = Upper_really), width = 0, alpha = 0.3) +
    geom_errorbarh(aes(xmin = Lower_original, xmax = Upper_original), height = 0, alpha = 0.3) +
    geom_smooth(method = "lm", color = "black") +
    geom_text_repel(aes(label = verb), family="fira", color="black")
```

```{r}
cor.test(mean_non_ngram_scores$Mean_original, mean_non_ngram_scores$Mean_really)

cor.test(mean_ngram_scores$Mean_bigram.csv, mean_ngram_scores$Mean_really_bigram.csv)
```