---
title: "exp3 graphs"
output: html_document
date: "2024-03-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("analysis/exp3_graphs.Rmd")
library(here)
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(tidyr)
library(ggrepel)
library(gghalves)
library(colorBlindness)
library(showtext)
library(lme4)
library(lmerTest)
library(patchwork)
library(ggpattern)
library(brms)

font_add("fira", "FiraSans-Regular.ttf")
font_add("firal", "FiraSans-Light.ttf")

theme_set(theme_light() + theme(text = element_text(size = 14, family = "fira")))

set.seed(123)
```

```{r}
results <- list.files(path = here("scores", "exp3"), pattern = "*.csv", full.names = TRUE) %>%
    read_csv(id = "file_name") %>%
    mutate(file_name = (basename(file_name))) %>%
    separate_wider_delim(file_name, delim = "_", names = c("a", "train_affectedness", "train_num", "seed", "b")) %>%
    select(!c(a, b)) %>%
    mutate(train_num = as.integer(train_num),
           train_affectedness = factor(train_affectedness, levels = c("low", "high")),
           affectedness = factor(affectedness, levels = c("low", "high"))
    ) %>%
    group_by(sentence) %>%
    mutate(id = cur_group_id())

# Filter results to only include sentences with the same affectedness in training and test
matched_results <- results %>%
    filter(affectedness == train_affectedness)
```

```{r}
mean_results <- matched_results %>%
    group_by(train_affectedness, train_num, affectedness) %>%
    summarise(
        result = Hmisc::smean.cl.boot(pass_drop) %>% t() %>% as.data.frame()
    ) %>%
    unnest(result)

no_training_high_affected <- mean_results %>%
    filter(train_num == 0) %>%
    mutate(affectedness = "high",
    train_num = train_num - 0.1) # addd jitter to avoid overlap

```

```{r}
training_data_labels <- c(
    "high" = "Highly affected verbal contexts in training",
    "low" = "Not"
)

average_passive_drop_no_training <- mean_results %>%
    filter(train_num == 0) %>%
    pull(Mean)

mean_results %>%
    rbind(no_training_high_affected) %>% 
    ggplot(aes(x = train_num, y = Mean, ymin = Lower, ymax = Upper, color = affectedness)) +
    scale_x_continuous(breaks = c(0, 10, 100, 1000, 2000), trans="pseudo_log") +
    geom_errorbar(width=0.1) +
    geom_point() +
    scale_y_continuous(limits = c(0, 18)) +
    geom_smooth(method = "lm") +
    labs(
        x = "Num. occurrences of novel verb in training corpus",
        y = "Mean passive drop",
        color = "Affectedness of verb contexts"
    ) +
    theme(legend.position = "bottom")
```


```{r}
# add id to each unique sentence
model_full <- lmer(
    pass_drop ~ train_num * train_affectedness +
    (1 + train_affectedness | seed) + (1 | id),
    data = matched_results,
    control = lmerControl(optimizer = "bobyqa"))

model_full %>% summary()

model_no_interactions <- lmer(
    pass_drop ~ train_num + train_affectedness +
    (1 + train_affectedness | seed) + (1 | id),
    data = matched_results,
    control = lmerControl(optimizer = "bobyqa"))

anova(model_full, model_no_interactions)
```

```{r}
# scale pass_drop, train_num, and affectedness
scaled_matched_results <- matched_results %>%
    mutate(
        pass_drop = scale(pass_drop),
        train_num = scale(log10(train_num+1e-10)),
    )

model_full <- brm(
    pass_drop ~ train_num * affectedness +
    (1 + train_num + affectedness | seed) + (1 + train_num + affectedness | id),
    data = scaled_matched_results, chains=4, cores=4, iter=8000,
    control = list(adapt_delta = 0.9)
)

model_full %>% summary()

plot(model_full)
# check Rhat graphically

pp_check(model_full,ndraws=100)
pp_check(model_full,type = "scatter_avg", ndraws = 100)

saveRDS(model_full, file = here("analysis", "exp3_model_full.rds"))

loaded_model <- readRDS(here("analysis", "exp3_model_full.rds"))

```

```{r}
plot(loaded_model)

pp_check(loaded_model,ndraws=100)
pp_check(loaded_model,type = "scatter_avg", ndraws = 100)

brms::rhat(loaded_model) |> head()

posterior_draws <- brms::as_draws_matrix(loaded_model)[,c("b_train_num:train_affectednesshigh", "b_train_num:affectednesshigh", "b_train_affectednesshigh:affectednesshigh", "b_train_num:train_affectednesshigh:affectednesshigh")]

bayesplot::mcmc_areas(posterior_draws)

loaded_model %>%
  tidybayes::tidy_draws() %>% 
  select(starts_with("b_train")) %>% 
  rename(train_num_train_affectedness = b_train_num:train_affectednesshigh) 
  
  %>% 
  pivot_longer(cols = everything()) %>% 
  ggplot(aes(x = value, y = name)) +
  tidybayes::stat_halfeye(fill = project_colors[1]) +
  ylab("") +
  geom_vline(aes(xintercept = 0), color = project_colors[2], size = 2)

```

### Original verbs

```{r}
train_dataset <- read_csv(here("decomp_dataset", "gpt4o_generated", "compiled_2412141957_deduped_train.csv"))

test_dataset <- read_csv(here("decomp_dataset", "gpt4o_generated", "compiled_2412141957_deduped_test.csv"))
```
