```{r}
library(lme4)
library(dplyr)
library(lmerTest)
```

### Experiment 1A

```{r}
head(scores_human)
```

```{r}
scores_human <- scores_human %>%
  mutate(verb_class = relevel(verb_class, ref = 'Agent-Patient'))

verb_class_lmm <- lmer(
  score ~ sentence_type + verb_class + sentence_type:verb_class + (1|frame) + (1 + sentence_type |id) + (1|verb),
  data = scores_human,
  REML = FALSE
)

summary(verb_class_lmm)
```

```{r}
scores_human_duration <- scores_human %>%
  filter(verb_class == "Duration") %>%
  mutate(verb = relevel(verb, ref = 'required'))

lmm_duration <- lmer(
  score ~ sentence_type + verb + sentence_type:verb + (1|frame) + (1|id),
  data = scores_human_duration,
  REML = FALSE
)

summary(lmm_duration)

```
```{r}
scores_human_price <- scores_human %>%
  filter(verb_class == "Price") %>%
  mutate(verb = relevel(verb, ref = 'earned'))

lmm_price <- lmer(
  score ~ sentence_type + verb + sentence_type:verb + (1|frame) + (1|id),
  data = scores_human_price,
  REML = FALSE
)

summary(lmm_price)

```
```{r}
scores_human_estimation <- scores_human %>%
  filter(verb_class == "Estimation") %>%
  mutate(verb = relevel(verb, ref = 'resembled'))

lmm_estimation <- lmer(
  score ~ sentence_type + verb + sentence_type:verb + (1|frame) + (1|id),
  data = scores_human_estimation,
  REML = FALSE
)

summary(lmm_estimation)

```
```{r}
scores_human_experiencer <- scores_human %>%
  filter(verb_class == "Experiencer-Theme") %>%
  mutate(verb = relevel(verb, ref = 'heard'))

lmm_experiencer <- lmer(
  score ~ sentence_type + verb + sentence_type:verb + (1|frame) + (1|id),
  data = scores_human_experiencer,
  REML = FALSE
)

summary(lmm_experiencer)
```




### Experiment 2
```{r}
summary(minicons)
```


```{r}

minicons_frequency_and_default <- minicons %>% 
    filter(corpus_type == "default" | corpus_type == "frequency")

freq_no_interaction <- lmer(
  pass_drop ~ corpus_type + (1 + corpus_type  |verb) + (1 + corpus_type|frame) + (1 | file_name), 
  data=minicons_frequency_and_default,
  REML = FALSE
)

freq_with_interaction <- lmer(
  pass_drop ~ corpus_type + altered + (1 + corpus_type|verb) + (1 + corpus_type|frame) + (1 | file_name), 
  data=minicons_frequency_and_default,
  REML = FALSE
)

summary(freq_with_interaction)

anova(freq_with_interaction, freq_no_interaction)
```


```{r}

minicons_swap_and_default <- minicons %>% 
    filter(corpus_type == "default" | corpus_type == "swap")

swap_no_interaction <- lmer(
  pass_drop ~ corpus_type + (1 + corpus_type |verb) + (1  |frame) + (1 | file_name), 
  data=minicons_swap_and_default,
  REML = FALSE
  )

swap_with_interaction <- lmer(
  pass_drop ~ corpus_type + altered + (1 + corpus_type |verb) + (1 |frame) + (1 | file_name), 
  data=minicons_swap_and_default,
  REML = FALSE
  )

swap_with_interaction

anova(swap_with_interaction, swap_no_interaction)
```
```{r}
minicons_swap_and_default_duration <- minicons_swap_and_default %>%
  filter(verb_class == "Duration") %>%
  mutate(verb = relevel(factor(verb), ref = 'took')
)

# no verb-level fixed effects
swap_no_interaction_no_verb <- lmer(
  pass_drop ~ corpus_type + altered + (1 + verb |frame) + (1 | file_name), 
  data=minicons_swap_and_default_duration,
  REML = FALSE
  )

# verb-level effects but not interaction
swap_no_interaction_by_verb <- lmer(
  pass_drop ~ corpus_type + altered + verb + (1 + verb|frame) + (1 | file_name), 
  data=minicons_swap_and_default_duration,
  REML = FALSE
  )

# verb-level effects and interaction between corpus and verb
swap_with_interaction_by_verb <- lmer(
  pass_drop ~ corpus_type + altered + verb + altered:verb + (1 + verb|frame) + (1 | file_name), 
  data=minicons_swap_and_default_duration,
  REML = FALSE
  )

summary(swap_with_interaction_by_verb)
anova(swap_no_interaction_no_verb, swap_no_interaction_by_verb)
anova(swap_no_interaction_by_verb, swap_with_interaction_by_verb)
```
```{r}
 0.000734 + 3.273942 - 3.903586
```


